### ISSUE TITLE
Pip3: not found

### ISSUE THREAD

**Issue by BenMyers84** [Clon1998/mobileraker#408] opened 2024-09-07 08:10 UTC
I am trying to install moonraker companion so I can get notifications via the app. I am using helper script to install it and no matter what I do at the end of the install I get /usr/data/mobileraker_companion/scripts/install.sh: line 197: pip3: not found
I don’t know how to resolve this.
I don’t know what details you need so I’ll just include anything I can think of.
I have a rooted nebula pad with my ender 3v3se. I’m SSH into the pad via Terminal on my Mac if that makes a difference.

**Comment by Clon1998** [comment] 2024-09-07 08:20
Closed as duplicate of

https://github.com/Clon1998/mobileraker_companion/issues/100

**Closed** 2024-09-07 08:20 UTC
