### ISSUE TITLE
JSON Parse error for printers with multiple extruders

### ISSUE THREAD

**Issue by rosscon** [Clon1998/mobileraker#97] opened 2023-01-07 11:45 UTC
**Describe the bug**
Receiving the below error on printers with multiple extruders with shared heaters, suspect it may be due to some of the fields in [config_extruder.dart](https://github.com/Clon1998/mobileraker/blob/master/lib/data/dto/config/config_extruder.dart) are not defined for multiple extruders e.g. nozzle & filament width.

**Screenshots**
App
![IMG_791E5D4921D2-1](https://user-images.githubusercontent.com/9072796/211148719-f9e764bd-8244-410e-8c7f-ae0a606db265.jpeg)

Klipper Extruder config
<img width="385" alt="Screenshot 2023-01-07 at 11 42 14" src="https://user-images.githubusercontent.com/9072796/211149037-edcb6739-e023-4928-b854-b96e6dae9901.png">

**Smartphone (please complete the following information):**
iOS 16.1.1

**Mobileraker-Version
2.0.2

**Comment by Clon1998** [comment] 2023-01-07 15:07
I will look into that. Most likely, it is caused by the shared config.
Since I am not running that setup, could you provide me with the JSON provided by the HTTP call `GET http://<YOUR PRINTER IP>/printer/objects/query?configfile` that fetches the entire config and that is actually parsed?

**Comment by rosscon** [comment] 2023-01-07 16:51
awesome cheers :)

json file attached
[configfile.json.zip](https://github.com/Clon1998/mobileraker/files/10366758/configfile.json.zip)

**Comment by mlee12382** [comment] 2023-02-26 13:35
Any update on this issue? I also have dual extruders with a shared nozzle and I am getting the same error.

**Comment by Clon1998** [comment] 2023-02-26 19:03
Sorry,
I was quite busy and the issue got lost.
I just had a look at it and found an error caused by my marshaling layer.
It interpreted the `[extruder_stepper ..]` config as an extruder and therefore, caused the bug!
However, I just committed a fix for that (efc65f0fd0093ae69753abb54b7729ebcaf2f452) and triggered a new release that should resolve that issue. Please let me know if It works now.

And again, apologies for my late response/fix.

**Comment by mlee12382** [comment] 2023-02-26 19:46
@Clon1998 awesome thanks for the update,  I will try it out when it's live and let you know if there are still any issues.

**Comment by Clon1998** [comment] 2023-02-26 19:47
> @Clon1998 awesome thanks for the update,  I will try it out when it's live and let you know if there are still any issues.

iOS version just got approved by apple. Android is still pending

**Comment by mlee12382** [comment] 2023-02-26 20:07
> > @Clon1998 awesome thanks for the update,  I will try it out when it's live and let you know if there are still any issues.
> 
> iOS version just got approved by apple. Android is still pending

Android update just went live and it seems to be working! Thanks again for the help.

**Closed** 2023-03-21 21:28 UTC
