### ISSUE TITLE
Newest update never stops loading

### ISSUE THREAD

**Issue by Leithian** [Clon1998/mobileraker#46] opened 2022-05-06 13:04 UTC
**Describe the bug**
Since the latest update, the dashboard screen doesn't load anymore, except the "pause" button. Also, the file thumbnails in the file explorer don't work anymore.
Also the printer settings only show a grey screen.

**To Reproduce**
1. Open the app
2. Never finish loading

**Expected behavior**
Seeing the dashboard

**Screenshots**
![Screenshot_20220506-145403](https://user-images.githubusercontent.com/6052614/167136204-08c92fbd-27e3-4605-8930-26a455988d30.png)
![Screenshot_20220506-145424](https://user-images.githubusercontent.com/6052614/167136223-c2abd066-048b-462d-bed1-8d066f822166.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 4XL
 - OS: Android
 - Version: 12

**Mobileraker-Version**
1.6.0-12

**Klipper versions**
- Klipper: v0.10.0-391-g722ad4a1
- Moonraker: v0.7.1-565-gfcfa563

**Comment by Clon1998** [comment] 2022-05-06 13:46
Hey, thanks for the feedback.
Did you upgrade or installed the app freshly?
If the first one is the case, can you test if the problem resolves by deleting the apps data and setting up the printer again?
I am pretty sure it's cause by the migration from local storage to Moonraker storage of the printer settings.

**Comment by Leithian** [comment] 2022-05-06 14:04
Yes, I upgraded, but also clearing the app data and setting it up again doesn't change what I get to see, the console and file viewer work but the dashboard doesn't.

**Comment by Clon1998** [comment] 2022-05-06 15:14
Interesting 🤔
I'll take a closer look at that tomorrow.
I need to setup an older version and test if sth. is still wrong with the settings migration.
Since the settings screen is not working and the dashboard is the only screen using the printer`s setting I am sure sth. is wrong there.

**Comment by padok** [comment] 2022-05-06 15:54
I also have this problem, in addition (I don't know if it's related) I can no longer open the printer settings to add a camera for example. It shows the settings for about 3-4s and then the screen turns completely gray, as shown below:

![2022-05-06 17 53 27](https://user-images.githubusercontent.com/32652531/167168540-39ef09a3-56ae-4d51-93bf-ea2469cd43c0.jpg)

**Comment by Leithian** [comment] 2022-05-06 16:02
I think it might be related, as I also have the same issue with the printer settings.

**Comment by Clon1998** [comment] 2022-05-06 16:30
Interesting that none of the RC testers reported the issue. However that's why I published a beta build to the store.
I now know that it's definitely related to the migration from local to remote storage for the printer settings.
I'll see if I am able to fix the issue until tomorrow.
Thanks for the feedback guys.
I'll let you guys know once I've published a new beta release fixing the issue.

**Comment by Leithian** [comment] 2022-05-06 19:17
I just found something, that I don't know how to make sense of: When I clear the app data, the printer gets removed as expected. But if clear app data, verify in the app that I would have to re-add my printer, uninstall and reinstall, my printer is back. Is there some storage through google cloud or something?

**Comment by Clon1998** [comment] 2022-05-06 19:43
> I just found something, that I don't know how to make sense of: When I clear the app data, the printer gets removed as expected. But if clear app data, verify in the app that I would have to re-add my printer, uninstall and reinstall, my printer is back. Is there some storage through google cloud or something?

No cloud-based sync. [Hive](https://github.com/hivedb/hive), the library I am using to persist data on a device. Internaly Hive uses Android's [shared preferences](https://developer.android.com/training/data-storage/shared-preferences) to store your data. As far as I know, the shared preference file created by apps is not removed during the removal/uninstall of an app. Thats why the settings are still available, even after deleting the app.

**Comment by Clon1998** [comment] 2022-05-06 19:46
I just pushed the fix with 05e46a9.
The problem was caused by a missing catch clause, resulting in an error while trying to fetch the settings for your printer (Presets, Invert-x,y,z ....).

**Comment by Leithian** [comment] 2022-05-06 19:48
But still it seems weird that I can delete my app data, don't see the printer in the app, uninstall and reinstall it and then get the printer back, even though the last state the app was in was without a printer...

**Comment by Clon1998** [comment] 2022-05-06 19:51
> But still it seems weird that I can delete my app data, don't see the printer in the app, uninstall and reinstall it and then get the printer back, even though the last state the app was in was without a printer...

Well, that's definitely weird. 
I have no explanation for that behaviour. However, I can guarantee you that no cloud sync is involved in mobileraker at the moment, you can always check the source code here.

**Comment by Leithian** [comment] 2022-05-06 19:59
> However, I can guarantee you that no cloud sync is involved in mobileraker at the moment, you can always check the source code here.
I believe you, cloud sync was just the first somewhat logical explanation for this behaviour. 

Thanks for the quick fix, I'll try it as soon as it's available!

**Comment by Clon1998** [comment] 2022-05-06 20:03
@Leithian, @padok,
I just submitted the new beta version.
I've attached the latest APK in case you guys want to test it earlier.

**Comment by padok** [comment] 2022-05-07 04:38
I can confirm, that the latest beta does fix the printer settings and the dashboard for me. Now only my cameras mjpg stream is does not load, but that could be user error.

**Comment by Leithian** [comment] 2022-05-07 07:18
I can also confirm that the dashboard and printer settings are fixed. For me, even the webcam is working, but the thumbnails in the file explorer are still not loading.

**Comment by Clon1998** [comment] 2022-05-07 13:00
> I can confirm, that the latest beta does fix the printer settings and the dashboard for me. Now only my cameras mjpg stream is does not load, but that could be user error.

Regarding the MJPEG stream, ensure that the correct address is set!
The cam is working on my side.

**Comment by Clon1998** [comment] 2022-05-07 16:24
> I can also confirm that the dashboard and printer settings are fixed. For me, even the webcam is working, but the thumbnails in the file explorer are still not loading.

I always receive the thumbnail images directly from moonraker. This is also working fine on my devices and also on the emulator.

**Comment by Clon1998** [comment] 2022-05-11 10:43
@Leithian, @padok did you guys manage to resolve your issues? 
So far I did not receive feedback regarding your issues.

**Comment by padok** [comment] 2022-05-11 11:13
Yes, for me the problem is solved, I switched my camera proxy to snapshot mode and my camera is also working again.

**Closed** 2022-05-13 09:36 UTC
