### ISSUE TITLE
Availabilty on F-Droid or FOSS catalogues

### ISSUE THREAD

**Issue by Cromagnonaut** [Clon1998/mobileraker#344] opened 2024-03-16 07:24 UTC
### Problem Description
Mobileraker not available on F-Droid (or alternatives).

### Proposed Solution
Adding support for FOSS app catalogues like [F-Droid](https://f-droid.org/en/).

### Alternatives Considered
Using the provided .apk, which is working well, but inconvenient in case of updates. Another alternative would using something like [AuroraOSS](https://auroraoss.com/)

### Additional Context
Since some users using de-googled phones, they do not have access to availability of "App-stores" depending on Google's services, like the Play-Store. Many of these users rely on FOSS app-catalogues (and the added repositories) like F-Droid.
The license should comply the [inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy/) of F-Droid, so it should technically be possible. 

I am willing to help were I can, but I have no knowledge in packaging-software at all.

**Comment by Clon1998** [comment] 2024-03-16 10:55
Duplicate of #20.
As stated [here](https://github.com/Clon1998/mobileraker/issues/20#issuecomment-1596215748), the app uses many services that do not comply with F-Droid's requirements.
Also, since I am the only Developer, I don't have the capacity to convert the current app and maintain a fork of it to comply with F-Droid's requirements.
If you don't want to use Google Play, you can download the newest version directly from GitHub.

**Closed by Clon1998** 2024-03-16 10:55 UTC
Labels: feature-request
