### ISSUE TITLE
UI customization

### ISSUE THREAD

**Issue by leitenky** [Clon1998/mobileraker#104] opened 2023-01-19 01:56 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to be able to add/remove/rearrange specific panels on the Dashboard (similar to the Mainsail dashboard config)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Clon1998** [comment] 2023-03-21 21:32
Duplicate of #11

**Closed by Clon1998** 2023-03-21 21:32 UTC
