### ISSUE TITLE
Add to slide over menu a shortcut to the local instance of Klipper

### ISSUE THREAD

**Issue by DrFate09** [Clon1998/mobileraker#178] opened 2023-06-19 15:40 UTC
To help fill in the gaps of functionality between Mainsail/Fluidd and Mobileraker, could you add a shortcut to our local instance of Mainsail/Fluidd so it can all be self-contained inside your app. Right now, I have to go between my browser and your app to access features that aren’t in Mobileraker yet.

Thinking of a shortcut link in the nav that will open up the current local printer instance of Mainsail/Fluidd that is accessible in your app, similar to an iframe. This is similar functionality to OrcaSlicer where you can add the IP address of your Klipper device and then can view the Mainsail interface within OrcaSlicer.

**Comment by Clon1998** [comment] 2023-08-11 19:09
Closed as duplicate of https://github.com/Clon1998/mobileraker/issues/103

**Closed by Clon1998** 2023-08-11 19:09 UTC
Labels: duplicate
