### ISSUE TITLE
Settings don‘t appear

### ISSUE THREAD

**Issue by matze-x2** [Clon1998/mobileraker#451] opened 2024-12-25 23:07 UTC
### Description
Settings Like caselight or fan 0-3 don’t appear, even after I customized my Layout, they are not visible.

### Steps to Reproduce
1. I go to overview .
2. I hold my finger on the screen till I can edit my layout.
3. I add the group „various“.
4. I save the Layout(I am a lifetime supporter).
5. The group don’t appear.

### Expected Behavior
Any suggest of which setting I need to active or a report that this is an actual bug and is going to be fixed 

### Screenshots
![IMG_3190](https://github.com/user-attachments/assets/0046d24a-22b9-41aa-abc7-5ef3ccd55dfb)
![IMG_3191](https://github.com/user-attachments/assets/8a7b97ea-2905-499f-96ab-61cf4d04e46d)

### Version Information

- Device-OS (Android/iOS): iOS 
- Mobileraker: 2.8.3-583
- Klipper: v0.10.0-530-g3387a9c23-dirty -> v0.12.0-404
- Moonraker: v0.7.1-609-gbdd0222-dirty -> v0.9.3-4

### Debug Logs
[mobileraker_2024-12-25T21-44-15.log](https://github.com/user-attachments/files/18247397/mobileraker_2024-12-25T21-44-15.log)
[mobileraker_2024-12-25T23-38-57.log](https://github.com/user-attachments/files/18247398/mobileraker_2024-12-25T23-38-57.log)
[mobileraker_2024-12-25T01-00-51.log](https://github.com/user-attachments/files/18247399/mobileraker_2024-12-25T01-00-51.log)
[mobileraker_2024-12-24T23-47-15.log](https://github.com/user-attachments/files/18247400/mobileraker_2024-12-24T23-47-15.log)
[mobileraker_2024-12-25T23-52-26.log](https://github.com/user-attachments/files/18247401/mobileraker_2024-12-25T23-52-26.log)

### Additional Context
It worked in the past and a few days ago it stopped out of nowhere, I didn’t change any settings neither on my printer nor in the app.

---

#### Checklist
To help us diagnose the issue, please ensure you've completed the following steps:
- [ X] Provided a clear bug description.
- [X ] Listed detailed steps to reproduce the issue.
- [X ] Described the expected behavior.
- [ X] Included the Mobileraker version you are using.
- [x] Attached Mobileraker's debug log files.
- [X ] Specified the version numbers of Klipper and Moonraker if applicable.

**Comment by Clon1998** [comment] 2024-12-25 23:30
Duplicate of #449

Waiting for a response i
In a different issue to deploy the hotfix for the broken misc card and the other issue.

**Closed** 2024-12-25 23:30 UTC
Labels: bug
