### ISSUE TITLE
Print Eta and bed level viewer

### ISSUE THREAD

**Issue by joelhughes004** [Clon1998/mobileraker#323] opened 2024-01-20 08:29 UTC
## Feature Request
Sorry about talking about the ETA, I didn't realize it was part of the new update. I was using two updates ago for the most part.

### Problem Description
I'm frustrated when I have to go back to the website view to grab the bed level indicator I would love for those to be in the app.

### Proposed Solution
I would love to have the bed level indicator with the other options like the extruder extrude feature

### Additional Context
Add any screenshots, examples, or additional context to help us understand your feature request better.

---

**Checklist**
To help us understand your feature request, please ensure you've covered the following points:
- [x] Provided a clear description of the problem you're facing.
- [x] Clearly outlined the proposed solution or feature.
- [ ] Mentioned any alternative solutions or ideas you've considered.
- [ ] Included any relevant context or supporting materials.

Your input is valuable in shaping the development of our project. Thank you for taking the time to submit your feature request!

**Comment by Clon1998** [comment] 2024-01-20 11:25
As mentioned by yourself. The ETA label was wrong and is fixed now.

The bed mesh/level FR is a duplicate of #196

**Closed by Clon1998** 2024-01-20 11:25 UTC
Labels: feature-request
