### ISSUE TITLE
Unable to start new print after cancelling print

### ISSUE THREAD

**Issue by cramsvik** [Clon1998/mobileraker#249] opened 2023-09-08 07:17 UTC
### Description
After cancelling a running print it is not possible to stat a new print from mobileraker. The print button for the file is grayed out. After restarting klipper it is again possible to start a new (or the same) file.

### Steps to Reproduce
1. Start a print
2. Cancel the print 
3. Go to a file and try to print it
4. The print-button is grayed out
5. Restart klipper
6. It is now possible to start a print

### Expected Behavior
After cancelling a print it should be possible to start a new print.

### Screenshots
If applicable, add screenshots to help explain the problem.

### Version Information
- Mobileraker: 2.5.2-246 (iPhone)
- Klipper: v0.11.0-271-g5f990f93 
- Moonraker: v0.8.0-138-gfe120952 

### Debug Logs
Please attach the log files generated by Mobileraker. You can find them by navigating to the app's settings page, scrolling to the bottom, and pressing the `Debug Logs` button.

### Additional Context
Add any other relevant context about the problem here.

---

#### Checklist
To help us diagnose the issue, please ensure you've completed the following steps:
- [ ] Provided a clear bug description.
- [ ] Listed detailed steps to reproduce the issue.
- [ ] Described the expected behavior.
- [ ] Included the Mobileraker version you are using.
- [ ] Attached Mobileraker's debug log files.
- [ ] Specified the version numbers of Klipper and Moonraker if applicable.
![IMG_4205](https://github.com/Clon1998/mobileraker/assets/7917520/a40ff3f9-3b10-4a48-b0d8-b02221b90578)
![IMG_4204](https://github.com/Clon1998/mobileraker/assets/7917520/09a4a3be-4750-40d6-9878-c297a699d0e0)
[mobileraker_2023-09-06T13-15-53.log](https://github.com/Clon1998/mobileraker/files/12556610/mobileraker_2023-09-06T13-15-53.log)
[mobileraker_2023-09-08T08-33-21.log](https://github.com/Clon1998/mobileraker/files/12556611/mobileraker_2023-09-08T08-33-21.log)
[mobileraker_2023-09-06T13-20-57.log](https://github.com/Clon1998/mobileraker/files/12556612/mobileraker_2023-09-06T13-20-57.log)
[mobileraker_2023-09-05T21-09-19.log](https://github.com/Clon1998/mobileraker/files/12556613/mobileraker_2023-09-05T21-09-19.log)
[mobileraker_2023-09-07T13-37-28.log](https://github.com/Clon1998/mobileraker/files/12556614/mobileraker_2023-09-07T13-37-28.log)

**Comment by Clon1998** [comment] 2023-09-08 07:58
Hey,
thanks for bringing that up.
Duplicate of #224,

Version 2.6.x is rolling out and should be available for all users by next Wednesday. It includes a [fix](https://github.com/Clon1998/mobileraker/blob/master/docs/changelog.md#260---2023-09-06) for that issue.

**Closed by Clon1998** 2023-09-08 07:58 UTC
Labels: bug
