### ISSUE TITLE
Mobileraker is not showing camera, menu icon and other section icons when in printing

### ISSUE THREAD

**Issue by salbang** [Clon1998/mobileraker#409] opened 2024-09-08 04:51 UTC
### Description
After upgrading to the latest version, both in iphone and android, mobileraker does not show camera and icons in dashboard while in printing.

### Steps to Reproduce
1. Overview -> Select printer in printing

2. Then the page is like as attached images.

### Expected Behavior
Dashboard should show camera and icons. 

### Screenshots
If applicable, add screenshots to help explain the problem.
iOS
![IMG_6355](https://github.com/user-attachments/assets/281607d7-1a2b-47d6-93ef-5b73806d2344)
![IMG_6356](https://github.com/user-attachments/assets/7d8d8fa8-040c-48a1-9caa-f93d1e6f9c82)

Android
![Screenshot_20240908_124529](https://github.com/user-attachments/assets/93ae89b8-05ea-4730-82e5-6e4becdf3e47)
![Screenshot_20240908_124711](https://github.com/user-attachments/assets/37ed1844-cea7-40bb-afcc-2f2c6c6d3f7f)

### Version Information

- Device-OS (Android/iOS): Both Android and iOS
- Mobileraker: 2.7.2 for both
- Klipper: v0.12.0-290
- Moonraker: v0.9.3

### Debug Logs
Please attach the log files generated by Mobileraker. You can find them by navigating to the app's settings page, scrolling to the bottom, and pressing the `Debug Logs` button.
iOS
[mobileraker_2024-09-08T12-38-16.log](https://github.com/user-attachments/files/16920798/mobileraker_2024-09-08T12-38-16.log)
[mobileraker_2024-09-08T12-36-27.log](https://github.com/user-attachments/files/16920799/mobileraker_2024-09-08T12-36-27.log)
[mobileraker_2024-09-08T12-33-57.log](https://github.com/user-attachments/files/16920800/mobileraker_2024-09-08T12-33-57.log)
[mobileraker_2024-09-08T11-56-05.log](https://github.com/user-attachments/files/16920801/mobileraker_2024-09-08T11-56-05.log)

Android
[mobileraker_2024-09-08T11-52-42.log](https://github.com/user-attachments/files/16920837/mobileraker_2024-09-08T11-52-42.log)
[mobileraker_2024-09-08T11-54-39.log](https://github.com/user-attachments/files/16920842/mobileraker_2024-09-08T11-54-39.log)
[mobileraker_2024-09-08T12-39-21.log](https://github.com/user-attachments/files/16920845/mobileraker_2024-09-08T12-39-21.log)
[mobileraker_2024-09-08T12-43-32.log](https://github.com/user-attachments/files/16920846/mobileraker_2024-09-08T12-43-32.log)
[mobileraker_2024-09-08T12-45-15.log](https://github.com/user-attachments/files/16920847/mobileraker_2024-09-08T12-45-15.log)

### Additional Context
Add any other relevant context about the problem here.
The problem did not exist before upgrading to 2.7.2 version.

---

#### Checklist
To help us diagnose the issue, please ensure you've completed the following steps:
- [x] Provided a clear bug description.
- [x] Listed detailed steps to reproduce the issue.

- [x] Described the expected behavior.
- [x] Included the Mobileraker version you are using.
- [x] Attached Mobileraker's debug log files.
- [x] Specified the version numbers of Klipper and Moonraker if applicable.

**Comment by Clon1998** [comment] 2024-09-08 09:14
Hey,
thanks for reporting this issue. I already saw it popping up in my error reporting and fixed it in 98c4806f1a7189059ab4e45b42fcd94eb5ebd8d0.

2.7.4 should be rolling out since yesterday. It is already available in the open beta on Android.

**Comment by Clon1998** [comment] 2024-09-08 09:24
Can you do me a favor and try 2.7.4 via the testflight version (https://testflight.apple.com/join/h9JwuyR0) and report back to me if the issue is resolved.

**Comment by salbang** [comment] 2024-09-08 12:02
![image](https://github.com/user-attachments/assets/126d7a6c-db8a-44ea-9fe1-62a73b913358)

I have checked the testflight, but the version is still 2.7.2 and I still have the same issue.

**Comment by Clon1998** [comment] 2024-09-08 12:17
> ![image](https://private-user-images.githubusercontent.com/12740762/365435971-126d7a6c-db8a-44ea-9fe1-62a73b913358.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3OTgxMjEsIm5iZiI6MTcyNTc5NzgyMSwicGF0aCI6Ii8xMjc0MDc2Mi8zNjU0MzU5NzEtMTI2ZDdhNmMtZGI4YS00NGVhLTlmZTEtNjJhNzNiOTEzMzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDEyMTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhOWE0N2RhMWE0NzdlOTIxY2UxNGU3MDdmN2Q5ZTkwZTU5YjRhY2FmMjRjZGZjZDBlMTU1OGY3YzNlYjhkYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tvx8TRW029uhmU7VyBxNaHDGU012vcF7nIhHvvhAsN4)
> 
> I have checked the testflight, but the version is still 2.7.2 and I still have the same issue.

Right its WE so apple will approve the version hopefully by monday!

**Comment by salbang** [comment] 2024-09-09 11:31
My android phone got 2.7.4 update yesterday and works fine now. Waiting for iphone update. Thank you.

**Comment by salbang** [comment] 2024-09-10 02:47
My iphone got 2.7.4 testflight update. Everything looks OK. Thank you for the update.

**Comment by mikec850** [comment] 2024-09-10 19:26
Joining the beta to get 2.7.4 fixed the issue for me on Android too.

**Comment by Clon1998** [comment] 2024-09-10 20:19
Awesome!
Will close the issue as 2.7.4 is rolling out slowly until next monday.

**Closed by Clon1998** 2024-09-10 20:19 UTC
Labels: bug
