### ISSUE TITLE
Is it possible to have the settings backed up as a file to either Google or our own cloud (e.g. nextcloud), so that it can be imported (sync) on other devices with ease?

Perhaps the use of WebDAV?

### ISSUE THREAD

**Issue by drumstick77** [Clon1998/mobileraker#393] opened 2024-07-30 20:49 UTC
### Problem Description
A clear and concise description of the problem or pain point you're experiencing. For example: "I'm always frustrated when..."

### Proposed Solution
A clear and concise description of the feature you'd like to see implemented.

### Alternatives Considered
If you've thought of any alternative solutions or features, please briefly describe them here.

### Additional Context
Add any screenshots, examples, or additional context to help us understand your feature request better.

---

**Checklist**
To help us understand your feature request, please ensure you've covered the following points:
- [ ] Provided a clear description of the problem you're facing.
- [ ] Clearly outlined the proposed solution or feature.
- [ ] Mentioned any alternative solutions or ideas you've considered.
- [ ] Included any relevant context or supporting materials.

Your input is valuable in shaping the development of our project. Thank you for taking the time to submit your feature request!

**Comment by Clon1998** [comment] 2024-07-30 21:55
Duplicate of #286

**Closed** 2024-07-30 21:55 UTC
Labels: feature-request
