### ISSUE TITLE
Power panel dissapeared

### ISSUE THREAD

**Issue by tbjr16** [Clon1998/mobileraker#348] opened 2024-03-26 00:26 UTC
### Description
A clear and concise description of the bug.
The power panel would show when my printer was off, to turn it on. Now that I've paid to be a lifetime supporter, nothing will load unless my printer is on. Sometimes it will load a shadow of it indefinitely.

### Steps to Reproduce
Go to moonraker
Turn printer off
Select that printer on Mobileraker
It only shows the klippy:error mcu unable to connect, which is normal, but the option to power it on has disappeared, or is an animated shadow of the panel

### Expected Behavior
I expected the power panel to be visible along with the Klippy:error

### Screenshots
If applicable, add screenshots to help explain the problem.

### Version Information

- Device-OS (Android/iOS): Android 
- Mobileraker: 2.6.13-417
- Klipper: v0.12.0-130-g40728e92
- Moonraker: v0.8.0-324-ga3e4dac5

**Comment by Clon1998** [comment] 2024-03-26 06:40
Hey,
this is a know bug which I already fixed in ios2.6.14. The version should be rolling out until Wednesday EOD.

Duplicate of #347

**Closed** 2024-03-30 23:42 UTC
Labels: bug
